version: "3"

services: 
    laravel-app:
        build: .
        ports:
          - "8080:80"
        volumes:
          - ./:/usr/share/nginx
    mysql-app:
        image: mysql:5.7.22
        command: --innodb-use-native-aio=0
        ports:
          - "3306:3306"
        volumes:
            - .docker/dbdata:/var/lib/mysql  
        environment:
            MYSQL_DATABASE: picpayon
            MYSQL_ROOT_PASSWORD: picpayhash
